### ISSUE TITLE
Speicherabfrage vor dem Schließen

### ISSUE THREAD

**Issue by SeparateThroughTime** [ptrckbnck/SQLChecker#12]
Es ist zwar kein Fehler in dem Sinne, aber gehört in jedes Programm finde ich:
Wenn ich das Programm schließe, wäre es schön, wenn ich gefragt werde, ob ich Nichtgespeichertes vorher speichern möchte.

**Comment by ptrckbnck** [comment]
Gut Idee. Kommt auf dIe TODO Liste

**Comment by ptrckbnck** [comment]
done mit Release Sose2021
