### ISSUE TITLE
Nach Öffnung eines Aufgabenblatts, kann SQLQuecker Reset-Skript nicht mehr finden

### ISSUE THREAD

**Issue by samimacl** [ptrckbnck/SQLChecker#13]
Hallo Patrick,

ich konnte einen Fehler bezüglich des Reset-Skript Handlings nachvollziehen bzw. reproduzieren. Meine Schritte:

1. Nach dem Öffnen von SQLChecker habe ich meine Config File geladen, spart mir Doppeleingaben der Einstellungen.

2. Reset-Skript ausgewählt

3. Eine Aufgabe mit Datei-Öffnen geöffnet

Durch Schritt 3. wird das Reset-Skript nicht mehr erkannt. In den Einstellungen befindet sich aber noch der gültige Pfad des im Schritt 2. ausgewählten Reset-Skripts. Als Workaround wäre es hier zu empfehlen, zuerst das Aufgabenblatt und dann das Reset-Skript zu laden. 

Liebe Grüße
Sascha

**Comment by SeparateThroughTime** [comment]
Datei öffnen öffnet eine bereits gespeicherte Datei mit dem Dateityp sqlc. In dieser werden auch die configs gespeichert. Füge einmal das Resetscript hinzu und speichere das ganze auch. Danach sollte beim öffnen (also dem Weiterarbeiten an der Aufgabe) auch die richtigen configs geladen werden.

Viele Grüße,
David
