### ISSUE TITLE
Fehler beim Starten unter Mac OS

### ISSUE THREAD

**Issue by donnerluetjen** [ptrckbnck/SQLChecker#2]
Ich kann das Programm nicht starten. Es ist Java v11 installiert.
Der beigefügte Screenshot zeigt die Fehlermeldung.
Die Doku beschreibt den Aufruf mit Versionsnummer und .jar-Endung. Solch einen File sehe ich aber auch nicht...
<img width="906" alt="screenshot sqlchecker" src="https://user-images.githubusercontent.com/20632/47931910-70b0d100-ded0-11e8-9a06-8a3093d10fb9.png">

**Comment by karstenT** [comment]
Hi,
ich nehme an, Du hast den Quellcode des Projektes herunter geladen. 
Die Jar-Datei findest Du auf der Release-Seite: https://github.com/ptrckbnck/SQLChecker/releases
... die erste Datei oben!

Falls Du einen Mac verwendest: Wie im anderen Issue beschrieben scheint es mit Java 11 unter Mac Probleme zu geben. Dann lieber auf Java 10.0.2 wechseln.

Grüße
Karsten Tolle

**Comment by donnerluetjen** [comment]
Danke.
Ich probier’s aus.

LG Ansgar

**Comment by ptrckbnck** [comment]
Wie Karsten sagte, musst du die jar-Datei ausführen.

**Comment by donnerluetjen** [comment]
Hallo Patrick,

nachdem ich jetzt eine Stunde rumprobiert habe, eine Java Version 10 auf meinem Mac zu installieren, gebe ich auf.

Offiziell ist die Version 10 nicht mehr zu bekommen. Eine SRE Version 10 kann ich zwar noch über die CHIP Seite beziehen, aber ohne SDK läuft das nicht.
Und mit SDK meldet sich die SDK Version.

Tut mir leid, ich kann mir vorstellen, wie blöd das ist, weil du so viel Arbeit investiert hast, um den Ablauf besser zu machen.

LG Ansgar

**Comment by ptrckbnck** [comment]
Hallo donnerluetjen,
hast du jetzt ein anderes Problem?  ~~Falls du Probleme mit der Installation von Java 10 hast. Probiere bitte diese Jar Datei für Java 11 https://github.com/ptrckbnck/SQLChecker/blob/javafx/SQLChecker-1.0.1.jar.~~ Falls das neue Problem immernoch besteht, erstelle bitte einen neues Issue.
