### ISSUE TITLE
 Could not create connection to database server

### ISSUE THREAD

**Issue by ghost1265** [ptrckbnck/SQLChecker#4]
Hallo,

ich habe Java 10.0.2 mit SQLChecker 1.0 und 
Java 11.01 mit SQLChecker 1.0.1 ausprobiert und bekomme bei beiden die gleiche Fehlermeldung:
 > Resette Datenbank.
> [ERROR] com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server.
> [ERROR] Resetten der Datenbank fehlgeschlagen
> [ERROR] SQLException (0): Could not create connection to database server.
Die Workbench funktioniert allerdings und hat Verbindung zum Server.
Ich benutzte Windows 10.

Was für Fehlerbehebungsmöglichkeiten gibt es?

**Comment by ptrckbnck** [comment]
Hallo  ghost1265,
danke für deinen Report.
Der SQLChecker konnte keine Verbindung zu deiner Datenbank aufbauen. Das kann verschiedene Ursachen haben. 
Benutzt du MariaDB oder MySQL? Welche Version? Welche Version der Workbench?
Wie baust du die Verbindung über die Worbench auf? Welche Eingaben verwendest du? 
Kannst du auf die Datenbank über die Konsole zugreifen? 
Ich kann deinen Fehler leider zur Zeit nicht nachvollziehen, ich brauche mehr Informationen.

Du kannst gerne auch das aktuelle Build https://github.com/ptrckbnck/SQLChecker/blob/bug/SQLChecker-1.0.3-alpha.jar testen.
Starte diese Version mit dem -v Flag im Terminal. Kopiere den vollen StackTrace der Exception hier hinein.

**Comment by ghost1265** [comment]
Hallo ptrckbnck,
ich benutze MySQL Workbench Version 8.0 CE. 
Über die Konsole komme ich zu MySQL Server Version 8.0.13
Wie baust du die Verbindung über die Workbench auf? - über den User root

über Konsole funktioniert:
 MySQL  JS > \connect --mx Martina@localhost
Creating an X protocol session to 'Martina@localhost'
Please provide the password for 'Martina@localhost': ********
Save password for 'Martina@localhost'? [Y]es/[N]o/Ne[v]er (default No): Y
Fetching schema names for autocompletion... Press ^C to stop.
Your MySQL connection id is 177 (X protocol)
Server version: 8.0.13 MySQL Community Server - GPL
No default schema selected; type \use <schema> to set one.

 MySQL  localhost:33060+ ssl  JS > \use airport
Default schema `airport` accessible through db.

 MySQL  localhost:33060+ ssl  airport  JS >


Testen der neuen Version 1.0.3-alpha:
> 1a: SQL Code wird ausgeführt.
> [ERROR] Ausführen des Codes fehlgeschlagen.
> [ERROR] SQLException (0): Public Key Retrieval is not allowed
> [ERROR] java.sql.SQLNonTransientConnectionException: Public Key Retrieval is not allowed
> [ERROR] 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
> [ERROR] 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
> [ERROR] 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
> [ERROR] 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:832)
> [ERROR] 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
> [ERROR] 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)
> [ERROR] 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:207)
> [ERROR] 	at com.mysql.cj.jdbc.MysqlDataSource.getConnection(MysqlDataSource.java:393)
> [ERROR] 	at com.mysql.cj.jdbc.MysqlDataSource.getConnection(MysqlDataSource.java:125)
> [ERROR] 	at com.mysql.cj.jdbc.MysqlDataSource.getConnection(MysqlDataSource.java:110)
> [ERROR] 	at de.unifrankfurt.dbis.config.DataSource.getConnection(DataSource.java:84)
> [ERROR] 	at de.unifrankfurt.dbis.config.GUIConfig.newConnection(GUIConfig.java:155)
> [ERROR] 	at de.unifrankfurt.dbis.GUI.SQLRunner.call(SQLRunner.java:65)
> [ERROR] 	at de.unifrankfurt.dbis.GUI.SQLRunner.call(SQLRunner.java:16)
> [ERROR] 	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
> [ERROR] 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
> [ERROR] 	at java.base/java.lang.Thread.run(Unknown Source)

Auch das Installieren auf einem anderen Windows 10 PC brachten nur dieselben Ergebnisse.
Ist die InnoDB Router Installation wichtig? Diese ist in beiden Fällen nicht durchgeführt, da mir die Parameter fehlen.

**Comment by ptrckbnck** [comment]
Ich habe die neue Version online gestellt, die Public Key Retrieval erlaubt. Das sollte dein Problem beheben.

**Comment by ghost1265** [comment]
Hallo ptrckbnck,

zwar wird die Zeitzone in den Einstellungen Datenbank mit dem Öffnen der Datei Blatt1.sqlc überschrieben, aber nachdem ich es manuell hinzugefügt habe, läufts.
Danke.

**Comment by ptrckbnck** [comment]
Hallo Ghost,
deine Einstellungen werden in der .sqlc Datei gespeichert. Wenn du diese lädst, wird die aktuelle Einstellung überschrieben!
Wenn du sie änderst, nachdem du die .sqlc geladen hast, sollte es keine Probleme geben.

Dieses Issue ist mit Release 1.0.3 gelöst.
