### ISSUE TITLE
How to build the project?

### ISSUE THREAD

**Issue by MyIgel** [ptrckbnck/SQLChecker#5]
It would be really nice to  have some words about how to build this application

**Comment by ptrckbnck** [comment]
Sure! Should be fairly easy.
It is a maven project. See: [LINK](https://maven.apache.org/) 
So, run `mvn package` is all you really (should) need.
SQLChecker is also using IntelliJ-IDE [LINK](https://www.jetbrains.com/idea/ )

If you have problems compiling please ask again!
