### ISSUE TITLE
Different display in notepad

### ISSUE THREAD

**Issue by Dan1337z** [ptrckbnck/SQLChecker#7]

**Comment by Dan1337z** [comment]
I don't know if this is much of an issue but if you export the txt-file and open it with notepad.exe (Windows) everything is in 1 line. I know that Windows generally uses "\r\n" while everything else uses "\n" for the newline recognition, maybe that is what's causing this.

**Comment by ptrckbnck** [comment]
Hello Dan,
you are right `\n` is the reason behind this behaviour. But that works as intended. Officially, SQLChecker does not support `\r\n`. 
If you want to read the File, use an other editor. I suggest [notepad++](https://notepad-plus-plus.org/).
