### ISSUE TITLE
Email of Code-Buddy

### ISSUE THREAD

**Issue by Fl4mer** [ptrckbnck/SQLChecker#8]
There is a little bug with the email of the code buddy.

In the created .txt the email of the buddy isn't set but your own email is shown two times.

Regards,
Tobi

**Comment by ptrckbnck** [comment]
Thanks for your feedback!
I am going to look into it.

**Comment by ptrckbnck** [comment]
It will be fixed in the upcoming release. It should not be a problem for the current exercise. No Hotfix will be released.

**Comment by ptrckbnck** [comment]
fixed in current release
